<?php
$Rechte =
[
"abrechnung" => ['zeiterfassung'],

"adresse" => ['abrechnungzeit',
'abrechnungzeitabgeschlossen',
'artikel',
'abrechnungzeitdelete',
'delkontakt',
'createdokument',
'kundeartikel',
'stundensatzdelete',
'stundensatz',
'newkontakt',
'minidetail',
'lohn',
'stundensatzedit',
'multilevel',
'addposition',
'adressebestellungmarkieren',
'ansprechpartner',
'ansprechpartnereditpopup',
'ansprechpartnerpopup',
'artikeleditpopup',
'auftraege',
'autocomplete',
'edit',
'downartikel',
'create',
'briefpdf',
'delete',
'delartikel',
'briefdelete',
'brief',
'dateien',
'email',
'kundevorlage',
'list',
'positioneneditpopup',
'ustprfedit',
'ustprfneu',
'rolecreate',
'lieferadresse',
'emaileditpopup',
'briefeditpopup',
'kontakthistorie',
'lieferadresseneditpopup',
'roledel',
'suchmaske',
'upartikel',
'rolledelete',
'lieferadressepopup',
'lieferantartikel',
'kontakthistorieeditpopup',
'ustpopup',
'lieferantvorlage',
'offenebestellungen',
'ustprf'],

ajax['ansprechpartner',
'lieferadresse',
'filter',
'table',
'tableposition',
'tooltipsuche'
'tcgetnextartikelnummer'],

angebot['addposition'],

api['shopimages'],

arbeitsnachweis['abschicken',
'addposition',
'copy',
'createfromproject',
'delarbeitsnachweisposition',
'list',
'editable',
'downarbeitsnachweisposition',
'delete',
'livetabelle',
'positionen',
'protokoll',
'uparbeitsnachweisposition',
'minidetail',
'pdf',
'edit',
'create',
'freigabe',
'positioneneditpopup',
'inlinepdf',
'abrechnung'],

artikel['ausreservieren',
'instueckliste',
'einkaufdisable',
'lagerlampe',
'schliessen',
'stuecklisteempty',
'provision',
'statistik',
'produktion',
'stuecklisteetiketten',
'minidetail',
'shopexport',
'stuecklisteimport',
'verkaufdisable',
'shopexportfiles',
'stuecklisteupload',
'umlagern',
'multilevel',
'ajaxwerte',
'delete',
'einkaufcopy',
'newlist',
'projekte',
'delstueckliste',
'einkaufdelete',
'offeneauftraege',
'verkaufeditpopup',
'offenebestellungen',
'reservierung',
'stueckliste',
'upstueckliste',
'wareneingang',
'downstueckliste',
'copy',
'edit',
'einkaufeditpopup',
'list',
'onlineshop',
'verkauf',
'seriennummern',
'verkaufcopy',
'create',
'editstueckliste',
'dateien',
'einkauf',
'etiketten',
'profisuche',
'verkaufdelete',
'artikelfreifelder',
'artikelfreifelderedit',
'artikelfreifeldersave',
'baumedit',
'srnlageredit',
'zertifikate',
'srnadresseedit',
'schnellanlegen',
'lagersync',
'chargedelete',
'copyedit',
'srnlagerdelete',
'mindesthaltbarkeitsdatum',
'demo',
'chargen',
'fremdnummern',
'thumbnail',
'eigenschaftencopy',
'artikelfreifelderdelete',
'mhddelete',
'einlagern',
'eigenschaftensuche',
'rohstoffeempty',
'shopimport',
'fremdnummerndelete',
'fremdnummernedit',
'auslagern',
'rohstoffe',
'baum',
'fremdnummernsave',
'eigenschaften',
'eigenschafteneditpopup',
'editrohstoffe',
'rabatt',
'belege',
'stuecklisteexport',
'baumajax',
'delrohstoffe',
'copysave',
'lager',
'baumdetail',
'eigenschaftendelete'],

artikelbaum['change',
'list',
'loeschen',
'detail',
'baumajax'],

artikeleigenschaften['create',
'list',
'delete',
'edit'],

artikeleinheit['create',
'edit',
'delete',
'list'],

artikelgruppen['delete',
'create',
'edit',
'list',

artikelkalkulation['delete',
'ekladen',
'kalkekladen',
'edittag',
'gesperrt',
'list',
'edit',
'savetag',
'save'],

artikelkategorien['delete',
'create',
'edit',
'list'],

artikel_fremdnummern['edit',
'save',
'delete',
'list'],

artikel_texte['delete',
'edit',
'list',
'save'],

auftrag['abschluss',
'inlinepdf',
'anfrage',
'abschicken',
'checkdisplay',
'downauftragposition',
'list',
'positionen',
'uststart',
'copy',
'edit',
'livetabelle',
'positioneneditpopup',
'search',
'verfuegbar',
'addposition',
'create',
'editable',
'minidetail',
'proforma',
'shopexport',
'versand',
'dateien',
'freigabe',
'nachlieferung',
'protokoll',
'teillieferung',
'ausversand',
'delauftragposition',
'rechnung',
'tracking',
'zahlungsmahnungswesen',
'berechnen',
'delete',
'lieferschein',
'pdf',
'reservieren',
'upauftragposition',
'zahlungsmail',
'summe'],

bestellung['auftrag',
'livetabelle',
'inlinepdf',
'abschicken',
'delbestellungposition',
'positioneneditpopup',
'addposition',
'delete',
'list',
'protokoll',
'downbestellungposition',
'copy',
'edit',
'minidetail',
'upbestellungposition',
'create',
'editable',
'pdf',
'dateien',
'freigabe',
'positionen'],

bestellvorschlag['create',
'tabelle',
'list'],

dateien['abschicken',
'archiv',
'artikel',
'freigabe',
'kundeuebernehmen',
'versand',
'lieferadresseneu',
'zahlung',
'protokoll',
'listfreigegebene',
'lieferadresseauswahl',
'edit',
'send',
'create',
'delete',
'list'],

etiketten['create',
'edit',
'list',
'delete'],

generic['edit',
'reiter_delete',
'reiter_up',
'reiter_down'],

gutschrift['zahlungseingang',
'zahlungsmahnungswesen',
'inlinepdf',
'abschicken',
'edit',
'minidetail',
'storno',
'addposition',
'editable',
'pdf',
'upgutschriftposition',
'create',
'freigabe',
'positionen',
'delete',
'positioneneditpopup',
'delgutschriftposition',
'list',
'protokoll',
'downgutschriftposition',
'livetabelle'],

hauptmenu['list'],

inhalt['delete',
'listshop',
'create',
'edit',
'list'],

inventur['abschicken',
'addposition',
'buchen',
'copy',
'create',
'createfromproject',
'freigabe',
'editable',
'edit',
'downinventurposition',
'delinventurposition',
'delete',
'list',
'livetabelle',
'minidetail',
'pdf',
'positionen',
'positioneneditpopup',
'protokoll',
'upinventurposition',
'automatisch'],

kalender['data',
'eventdata',
'taskstatus',
'update',
'delete',
'list'],

kasse['exportieren'],

lager['auslagernproduktion'
lager['deleteplatz'
lager['buchenzwischenlagerdelete'
lager['lagerpdfsammelentnahme'
lager['inventurladen'
lager['artikelentfernen'
lager['artikelentfernenreserviert'
lager['artikelfuerlieferungen'
lager['ausgehend'
lager['bestand'
lager['buchenzwischenlager'
lager['bucheneinlagern'
lager['buchenauslagern'
lager['buchen'
lager['bewegungpopup'
lager['bewegung'
lager['create'
lager['delete'
lager['edit'
lager['etiketten'
lager['platzeditpopup'
lager['list'
lager['platz'
lager['inventur'
lager['produktionslager'
lager['regaletiketten'
lager['reservierungen'
lager['zwischenlager'
lager['nachschublager'

lagermobil['artikelentfernen'
lagermobil['ausgehend'
lagermobil['auslagernproduktion'
lagermobil['auslagern'
lagermobil['artikelentfernenreserviert'
lagermobil['bewegung'
lagermobil['buchen'
lagermobil['buchenauslagern'
lagermobil['bucheneinlagern'
lagermobil['artikelfuerlieferungen'
lagermobil['buchenzwischenlager'
lagermobil['delete'
lagermobil['buchenzwischenlagerdelete'
lagermobil['create'
lagermobil['differenzen'
lagermobil['deleteplatz'
lagermobil['bewegungpopup'
lagermobil['edit'
lagermobil['einlagern'
lagermobil['differenzenlagerplatz'
lagermobil['differenzenlagerplatzsave'
lagermobil['etiketten'
lagermobil['inhalt'
lagermobil['differenzenlagerplatzedit'
lagermobil['lagerpdfsammelentnahme'
lagermobil['letztebewegungen'
lagermobil['platz'
lagermobil['lpumlagern'
lagermobil['nachschublager'
lagermobil['list'
lagermobil['reservierungen'
lagermobil['produktionslager'
lagermobil['schnelleinlagern'
lagermobil['zwischenlager'
lagermobil['regaletiketten'
lagermobil['wert'
lagermobil['platzeditpopup'

lieferschein['paketmarke'
lieferschein['inlinepdf'
lieferschein['abschicken'
lieferschein['addposition'
lieferschein['copy'
lieferschein['create'
lieferschein['delete'
lieferschein['dellieferscheinposition'
lieferschein['list'
lieferschein['freigabe'
lieferschein['editable'
lieferschein['edit'
lieferschein['downlieferscheinposition'
lieferschein['livetabelle'
lieferschein['minidetail'
lieferschein['pdf'
lieferschein['positionen'
lieferschein['positioneneditpopup'
lieferschein['uplieferscheinposition'
lieferschein['protokoll'

linkeditor['delete'
linkeditor['massedit'
linkeditor['deleterule'
linkeditor['help'
linkeditor['list'
linkeditor['status'

lohnabrechnung['details'
lohnabrechnung['list'
lohnabrechnung['minidetail'
lohnabrechnung['monatsuebersicht'

mobile['auslagern'
mobile['cancel'
mobile['einlagern'
mobile['list'
mobile['umlagern'

multilevel['create'
multilevel['edit'
multilevel['list'

multiorderpicking['edit'
multiorderpicking['fehler'
multiorderpicking['list'
multiorderpicking['label'
multiorderpicking['minidetail'
multiorderpicking['versandzentrum'
multiorderpicking['listmobile'

paketmarke['create'
paketmarke['tracking'

rechnung['zahlungseingang'
rechnung['forderungsverlust'
rechnung['inlinepdf'
rechnung['manuellbezahltentfernen'
rechnung['manuellbezahltmarkiert'
rechnung['multilevel'
rechnung['abschicken'
rechnung['destop'
rechnung['freigabe'
rechnung['mahnpdf'
rechnung['search'
rechnung['addposition'
rechnung['downrechnungposition'
rechnung['gutschrift'
rechnung['mahnwesen'
rechnung['pdf'
rechnung['skonto'
rechnung['copy'
rechnung['dta'
rechnung['mahnweseneinstellungen'
rechnung['positionen'
rechnung['stop'
rechnung['create'
rechnung['edit'
rechnung['lastschrift'
rechnung['positioneneditpopup'
rechnung['uprechnungposition'
rechnung['delete'
rechnung['editable'
rechnung['list'
rechnung['protokoll'
rechnung['delrechnungposition'
rechnung['livetabelle'
rechnung['minidetail'
rechnung['zahlungsmahnungswesen'

rechnungslauf['archiv'
rechnungslauf['create'
rechnungslauf['edit'
rechnungslauf['list'
rechnungslauf['mahnwesen'
rechnungslauf['zahlungseingang'
rechnungslauf['artikel'
rechnungslauf['rechnungslauf'

reisekostenart['create'
reisekostenart['delete'
reisekostenart['edit'
reisekostenart['list'

seriennummern['create'
seriennummern['edit'
seriennummern['delete'
seriennummern['lager'
seriennummern['log'
seriennummern['list'
seriennummern['produktion'
stornierungen['create'
stornierungen['edit'
stornierungen['bezahlt'
stornierungen['list'

survey['list'

ticket_old['antwort'
ticket_old['beantwortet'
ticket_old['delete'
ticket_old['edit'
ticket_old['freigabe'
ticket_old['create'
ticket_old['list'
ticket_old['assistent'

uebersetzung['main'

verrechnungsart['create'
verrechnungsart['delete'
verrechnungsart['edit'
versanderzeugen['einzel'
versanderzeugen['frankieren'
versanderzeugen['list'
versanderzeugen['main'
versanderzeugen['offene'
versanderzeugen['korrektur'
versanderzeugen['gelesen'
versanderzeugen['delete'

vmajax['vmautoversanddrucken',
'vmautoversanddruckencheckbatch'],

wareneingang['main',
'removevorgang',
'vorgang',
'help',
'create',
'distriabschluss',
'distribution',
'distrietiketten',
'distriinhalt',
'list',
'paketabschliessen',
'paketabsender',
'paketannahme',
'paketetikett',
'rmalist',
'rmadetail',
'paketzustand',
'manuellerfassen',
'minidetail'],

warteschlangen['create',
'delete',
'edit',
'list'],

welcome['help',
'info',
'list',
'start',
'settings',
'addnote',
'delnote',
'movenote',
'oknote',
'pinwand',
'upgrade',
'startseite',
'css',
'logo',
'editvorgang',
'logout',
'main',
'login',
'vorgang',
'removevorgang'],

wiki['alle',
'create',
'delete',
'edit',
'list',
'rename',
'dateien'],

wizard['adresse',
'create',
'list'],

zeiterfassung['abrechnenpdf',
'listuser',
'minidetail',
'arbeitspaket',
'create',
'delete',
'details',
'edit',
'list']
]




?>
