<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateProjektTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        if (!app()->environment('production')) {
            Schema::create('projekt', function (Blueprint $table) {
                $table->id();
                $table->string('name', 128);
                $table->string('abkuerzung', 128)->index('abkuerzung');
                $table->text('verantwortlicher');
                $table->text('beschreibung');
                $table->text('sonstiges');
                $table->string('aktiv', 10);
                $table->string('farbe', 16);
                $table->integer('autoversand');
                $table->integer('checkok');
                $table->integer('portocheck');
                $table->integer('automailrechnung');
                $table->string('checkname', 64);
                $table->integer('zahlungserinnerung');
                $table->string('zahlungsmailbedinungen');
                $table->integer('folgebestaetigung');
                $table->integer('stornomail');
                $table->integer('kundenfreigabe_loeschen');
                $table->integer('autobestellung');
                $table->integer('speziallieferschein');
                $table->integer('lieferscheinbriefpapier');
                $table->integer('speziallieferscheinbeschriftung');
                $table->integer('firma');
                $table->integer('geloescht');
                $table->text('logdatei');
                $table->integer('reservierung')->nullable();
                $table->integer('oeffentlich')->default(0);
                $table->integer('kunde')->nullable()->index('kunde');
                $table->decimal('gesamtstunden_max', 10, 2);
                $table->integer('auftragid')->nullable();
                $table->integer('verkaufszahlendiagram')->nullable();
                $table->string('standardversandart');
                $table->string('dpdkundennr', 128);
                $table->string('dhlkundennr', 128);
                $table->string('dpdpfad')->nullable();
                $table->string('dhlpfad')->nullable();
                $table->string('dhlzahlungmandant', 3);
                $table->string('dhlzahlungmandantinternational', 3);
                $table->integer('dhlretourenschein');
                $table->string('upspfad');
                $table->string('abrechnungsart', 128);
                $table->string('kommissionierverfahren', 128);
                $table->integer('wechselaufeinstufig')->nullable();
                $table->integer('projektuebergreifendkommisionieren')->nullable();
                $table->string('absendeadresse')->nullable();
                $table->string('absendename')->nullable();
                $table->text('absendesignatur');
                $table->integer('autodruckrechnung')->nullable();
                $table->integer('autodruckversandbestaetigung')->nullable();
                $table->integer('automailversandbestaetigung')->nullable();
                $table->integer('autodrucklieferschein')->nullable();
                $table->integer('automaillieferschein')->nullable();
                $table->integer('autodruckstorno')->nullable();
                $table->integer('autodruckanhang')->nullable();
                $table->integer('automailanhang')->nullable();
                $table->integer('eigenernummernkreis')->nullable();
                $table->string('next_angebot', 64)->nullable();
                $table->string('next_auftrag', 64)->nullable();
                $table->string('next_rechnung', 64)->nullable();
                $table->string('next_lieferschein', 64)->nullable();
                $table->string('next_arbeitsnachweis', 64)->nullable();
                $table->string('next_reisekosten', 64)->nullable();
                $table->string('next_bestellung', 64)->nullable();
                $table->string('next_gutschrift', 64)->nullable();
                $table->string('next_kundennummer', 64)->nullable();
                $table->string('next_lieferantennummer', 64)->nullable();
                $table->string('next_mitarbeiternummer', 64)->nullable();
                $table->string('next_waren', 64)->nullable();
                $table->string('next_produktion', 64)->nullable();
                $table->string('next_sonstiges', 64)->nullable();
                $table->string('next_anfrage', 64)->nullable();
                $table->string('next_artikelnummer', 64)->nullable();
                $table->integer('shopzwangsprojekt')->default(0);
                $table->decimal('steuersatz_normal', 10, 2)->default(19.00);
                $table->decimal('steuersatz_zwischen', 10, 2)->default(7.00);
                $table->decimal('steuersatz_ermaessigt', 10, 2)->default(7.00);
                $table->decimal('steuersatz_starkermaessigt', 10, 2)->default(7.00);
                $table->decimal('steuersatz_dienstleistung', 10, 2)->default(7.00);
                $table->string('waehrung', 3)->default('EUR');
                $table->integer('eigenesteuer')->default(0);
                $table->integer('druckerlogistikstufe1')->default(0);
                $table->integer('druckerlogistikstufe2')->default(0);
                $table->text('dhlformat')->nullable();
                $table->text('dpdformat')->nullable();
                $table->integer('paketmarke_einzeldatei')->nullable();
                $table->integer('autodruckerrechnung')->default(1);
                $table->integer('autodruckerlieferschein')->default(1);
                $table->integer('autodruckeranhang')->default(1);
                $table->integer('autodruckrechnungmenge')->default(1);
                $table->integer('autodrucklieferscheinmenge')->default(1);
                $table->boolean('selbstabholermail')->default(0);
                $table->boolean('eanherstellerscan')->default(0);
                $table->boolean('dhlintodb')->default(0);
                $table->boolean('intraship_enabled')->default(0);
                $table->integer('intraship_drucker')->default(0);
                $table->boolean('intraship_testmode')->default(0);
                $table->string('intraship_user', 64)->default('');
                $table->string('intraship_signature', 64)->default('');
                $table->string('intraship_ekp', 64)->default('');
                $table->string('intraship_api_user', 64)->default('');
                $table->string('intraship_api_password', 64)->default('');
                $table->string('intraship_company_name', 64)->default('');
                $table->string('intraship_street_name', 64)->default('');
                $table->string('intraship_street_number', 64)->default('');
                $table->string('intraship_zip', 12)->default('');
                $table->string('intraship_country', 64)->default('germany');
                $table->string('intraship_city', 64)->default('');
                $table->string('intraship_email', 64)->default('');
                $table->string('intraship_phone', 64)->default('');
                $table->string('intraship_internet', 64)->default('');
                $table->string('intraship_contact_person', 64)->default('');
                $table->string('intraship_account_owner', 64)->default('');
                $table->string('intraship_account_number', 64)->default('');
                $table->string('intraship_bank_code', 64)->default('');
                $table->string('intraship_bank_name', 64)->default('');
                $table->string('intraship_iban', 64)->default('');
                $table->string('intraship_bic', 64)->default('');
                $table->integer('intraship_WeightInKG')->default(5);
                $table->integer('intraship_LengthInCM')->default(50);
                $table->integer('intraship_WidthInCM')->default(50);
                $table->integer('intraship_HeightInCM')->default(50);
                $table->string('intraship_PackageType', 8)->default('PL');
                $table->boolean('seriennummernerfassen')->default(1);
                $table->string('dpdendung', 64)->default('.csv');
                $table->string('dhlendung', 64)->default('.csv');
                $table->boolean('nachnahmecheck')->default(1);
                $table->boolean('kasse_lieferschein_anlegen')->default(0);
                $table->string('kasse_lagerprozess', 64)->default('');
                $table->string('kasse_belegausgabe', 64)->default('');
                $table->integer('kasse_drucker')->default(0);
                $table->integer('kasse_lieferschein')->default(1);
                $table->integer('kasse_rechnung')->default(1);
                $table->integer('kasse_lieferschein_doppel')->default(1);
                $table->integer('kasse_lager')->default(0);
                $table->integer('kasse_laufkundschaft')->default(0);
                $table->integer('autostuecklistenanpassung');
                $table->string('kasse_text_bemerkung', 64)->default('Interne Bemerkung');
                $table->string('kasse_text_freitext', 64)->default('Text auf Beleg');
                $table->integer('kasse_konto')->default(0);
                $table->boolean('kasse_zahlung_bar')->default(1);
                $table->boolean('kasse_zahlung_ec')->default(1);
                $table->boolean('kasse_zahlung_kreditkarte')->default(1);
                $table->boolean('kasse_zahlung_ueberweisung')->default(1);
                $table->boolean('kasse_zahlung_paypal')->default(0);
                $table->boolean('kasse_extra_rechnung')->default(1);
                $table->boolean('kasse_extra_quittung')->default(0);
                $table->boolean('kasse_extra_gutschein')->default(0);
                $table->boolean('kasse_extra_rabatt_prozent')->default(1);
                $table->boolean('kasse_extra_rabatt_euro')->default(0);
                $table->integer('tracking_substr_start')->default(8);
                $table->boolean('tracking_remove_kundennummer')->default(1);
                $table->boolean('tracking_substr_length')->default(0);
                $table->string('billsafe_merchantId', 64)->default('');
                $table->string('billsafe_merchantLicenseSandbox', 64)->default('');
                $table->string('billsafe_merchantLicenseLive', 64)->default('');
                $table->string('billsafe_applicationSignature', 64)->default('');
                $table->string('billsafe_applicationVersion', 64)->default('');
                $table->boolean('kasse_extra_keinbeleg')->default(0);
                $table->boolean('kasse_adresse_erweitert')->default(1);
                $table->boolean('kasse_zahlungsauswahl_zwang')->default(1);
                $table->boolean('kasse_button_entnahme')->default(0);
                $table->string('kasse_vorauswahl_andrede', 64)->default('herr');
                $table->boolean('kasse_erweiterte_lagerabfrage')->default(0);
                $table->string('kasse_vorauswahl_anrede', 64)->default('herr');
                $table->string('intraship_exportgrund', 64)->default('');
                $table->integer('kasse_rabatt_artikel')->default(0);
                $table->boolean('kasse_button_trinkgeld')->default(0);
                $table->string('land', 2)->default('DE');
                $table->integer('kasse_preisgruppe')->default(0);
                $table->integer('filialadresse')->default(0);
                $table->integer('versandprojektfiliale')->default(0);
                $table->boolean('etiketten_positionen')->default(0);
                $table->integer('etiketten_drucker')->default(0);
                $table->integer('etiketten_art')->default(0);
                $table->boolean('versandzweigeteilt')->default(0);
                $table->integer('go_drucker')->default(0);
                $table->string('go_apiurl_prefix', 128)->default('');
                $table->string('go_apiurl_postfix', 128)->default('');
                $table->string('go_apiurl_user', 128)->default('');
                $table->string('go_username', 128)->default('');
                $table->string('go_password', 128)->default('');
                $table->string('go_ax4nr', 128)->default('');
                $table->string('go_name1', 128)->default('');
                $table->string('go_name2', 128)->default('');
                $table->string('go_abteilung', 128)->default('');
                $table->string('go_strasse1', 128)->default('');
                $table->string('go_strasse2', 128)->default('');
                $table->string('go_hausnummer', 10)->default('');
                $table->string('go_plz', 64)->nullable();
                $table->string('go_ort', 128)->default('');
                $table->string('go_land', 128)->default('');
                $table->decimal('go_standardgewicht', 10, 2)->nullable();
                $table->string('go_format', 64)->nullable();
                $table->string('go_ausgabe', 64)->nullable();
                $table->string('secupay_apikey', 64)->default('');
                $table->string('secupay_url', 64)->default('');
                $table->boolean('secupay_demo')->default(0);
                $table->integer('differenz_auslieferung_tage')->default(2);
                $table->boolean('kasse_zahlung_bar_bezahlt')->default(0);
                $table->boolean('kasse_zahlung_ec_bezahlt')->default(0);
                $table->boolean('kasse_zahlung_kreditkarte_bezahlt')->default(0);
                $table->boolean('kasse_zahlung_ueberweisung_bezahlt')->default(0);
                $table->boolean('kasse_zahlung_paypal_bezahlt')->default(0);
                $table->boolean('kasse_quittung_rechnung')->default(0);
                $table->integer('kasse_bondrucker')->default(0);
                $table->boolean('kasse_bondrucker_aktiv')->default(0);
                $table->boolean('kasse_bondrucker_qrcode')->default(0);
                $table->string('kasse_bon_zeile1', 64)->default('WaWision Store');
                $table->text('kasse_bon_zeile2');
                $table->text('kasse_bon_zeile3');
                $table->boolean('produktionauftragautomatischfreigeben')->default(0);
                $table->boolean('versandlagerplatzanzeigen')->default(0);
                $table->string('intraship_partnerid', 64)->default('01');
                $table->boolean('intraship_retourenlabel')->default(0);
                $table->string('next_kalkulation', 128);
                $table->string('intraship_retourenaccount', 16)->default('');
                $table->string('status', 64)->default('');
                $table->boolean('kasse_button_schublade')->default(0);
                $table->text('absendegrussformel');
                $table->boolean('versandartikelnameausstammdaten')->default(0);
                $table->string('intraship_partnerid_welt', 64)->default('');
                $table->boolean('kommissionierlauflieferschein')->default(0);
                $table->boolean('mahnwesen')->default(1);
                $table->boolean('eanherstellerscanerlauben')->default(0);
                $table->boolean('kasse_button_einlage')->default(0);
                $table->integer('projektlager')->default(0);
                $table->boolean('tracing_substr_length')->default(0);
                $table->string('ups_api_user', 128)->default('');
                $table->string('ups_api_password', 128)->default('');
                $table->string('ups_api_key', 128)->default('');
                $table->string('ups_accountnumber', 128)->default('');
                $table->string('ups_company_name', 128)->default('');
                $table->string('ups_street_name', 128)->default('');
                $table->string('ups_street_number', 10)->default('');
                $table->string('ups_zip', 64)->default('');
                $table->string('ups_country', 2)->default('');
                $table->string('ups_city', 128)->default('');
                $table->string('ups_email', 128)->default('');
                $table->string('ups_phone', 128)->default('');
                $table->string('ups_internet', 128)->default('');
                $table->string('ups_contact_person', 128)->default('');
                $table->decimal('ups_WeightInKG', 10, 2)->nullable();
                $table->integer('ups_drucker')->default(0);
                $table->string('ups_ausgabe', 64)->default('GIF');
                $table->string('ups_package_code', 64)->default('02');
                $table->string('ups_package_description', 128)->default('Customer Supplied');
                $table->string('ups_service_code', 64)->default('65');
                $table->string('ups_service_description', 128)->default('UPS Saver');
                $table->integer('autodruckrechnungdoppel')->default(0);
                $table->string('next_preisanfrage', 128);
                $table->string('next_proformarechnung', 128);
                $table->integer('intraship_exportdrucker')->default(0);
                $table->boolean('multiorderpicking')->default(0);
                $table->text('gsmailhtmlbody');
                $table->text('gsmailhtmltext1');
                $table->string('gsmailhtmlbetreff');
                $table->text('gsmailhtmltext2');
                $table->boolean('autodruckrechnungstufe1')->default(0);
                $table->boolean('chargenerfassen')->default(0);
                $table->boolean('mhderfassen')->default(0);
                $table->boolean('autodruckkommissionierscheinstufe1')->default(0);
                $table->integer('kasse_bondrucker_anzahl')->default(1);
                $table->boolean('kasse_rksv_aktiv')->default(0);
                $table->string('kasse_rksv_tool', 64)->default('');
                $table->string('kasse_rksv_kartenleser', 128)->default('');
                $table->string('kasse_rksv_karteseriennummer', 128)->default('');
                $table->string('kasse_rksv_kartepin', 128)->default('');
                $table->string('kasse_rksv_aeskey', 128)->default('');
                $table->text('kasse_rksv_publiczertifikat');
                $table->text('kasse_rksv_publiczertifikatkette');
                $table->string('kasse_rksv_kassenid', 128)->default('');
                $table->decimal('ups_LengthInCM', 10, 2)->nullable();
                $table->decimal('ups_WidthInCM', 10, 2)->nullable();
                $table->decimal('ups_HeightInCM', 10, 2)->nullable();
                $table->integer('standardlager')->default(0);
                $table->integer('standardlagerproduktion')->default(0);
                $table->boolean('applyWomStuecklistenFix')->default(0);
                $table->string('nachnahme_kontoname', 55)->nullable();
                $table->string('nachnahme_kontoiban', 55)->nullable();
                $table->string('nachnahme_kontobic', 55)->nullable();
                $table->boolean('retourenlabel')->nullable()->default(0);
                $table->text('freifeld1')->nullable();
                $table->text('freifeld2')->nullable();
                $table->text('freifeld3')->nullable();
                $table->text('freifeld4')->nullable();
                $table->text('freifeld5')->nullable();
                $table->text('freifeld6')->nullable();
                $table->text('freifeld7')->nullable();
                $table->text('freifeld8')->nullable();
                $table->text('freifeld9')->nullable();
                $table->text('freifeld10')->nullable();
                $table->string('mahnwesen_abweichender_versender', 40)->default('');
                $table->integer('lagerplatzlieferscheinausblenden')->default(0);
                $table->boolean('etiketten_sort')->default(0);
                $table->boolean('autodruckrechnungstufe1menge')->default(1);
                $table->boolean('autodruckrechnungstufe1mail')->default(0);
                $table->boolean('autodruckkommissionierscheinstufe1menge')->default(1);
                $table->boolean('kasse_bondrucker_freifeld')->default(0);
                $table->integer('kasse_gutschrift')->default(1);
                $table->boolean('rechnungerzeugen')->default(0);
                $table->boolean('pos_artikeltexteuebernehmen')->default(0);
                $table->boolean('pos_anzeigenetto')->default(0);
                $table->boolean('pos_zwischenspeichern')->default(0);
                $table->boolean('kasse_button_belegladen')->default(0);
                $table->boolean('kasse_button_storno')->default(0);
                $table->boolean('pos_kundenalleprojekte')->default(0);
                $table->boolean('pos_artikelnurausprojekt')->default(0);
                $table->boolean('allechargenmhd')->default(0);
                $table->integer('anzeigesteuerbelege')->default(0);
                $table->boolean('pos_grosseansicht')->default(0);
                $table->integer('preisberechnung')->default(0);
                $table->string('steuernummer', 32)->default('');
                $table->boolean('paketmarkeautodrucken')->default(0);
                $table->string('orderpicking_sort', 26)->default('');
                $table->boolean('deactivateautoshipping')->default(0);
                $table->string('zahlungsweise', 64)->default('');
                $table->string('zahlungsweiselieferant', 64)->default('');
                $table->string('versandart', 64)->default('');
                $table->text('email_html_template')->nullable();
                $table->string('next_retoure', 64)->nullable()->default('');
                $table->string('next_verbindlichkeit', 128)->nullable()->default('');
                $table->boolean('pos_disable_single_entries')->nullable()->default(0);
                $table->boolean('pos_disable_single_day')->nullable()->default(0);
                $table->boolean('pos_disable_counting_protocol')->nullable()->default(0);
                $table->boolean('pos_disable_signature')->nullable()->default(0);
                $table->string('steuer_erloese_inland_normal', 10)->nullable()->default('');
                $table->string('steuer_aufwendung_inland_normal', 10)->nullable()->default('');
                $table->string('steuer_erloese_inland_ermaessigt', 10)->nullable()->default('');
                $table->string('steuer_aufwendung_inland_ermaessigt', 10)->nullable()->default('');
                $table->string('steuer_erloese_inland_nichtsteuerbar', 10)->nullable()->default('');
                $table->string('steuer_aufwendung_inland_nichtsteuerbar', 10)->nullable()->default('');
                $table->string('steuer_erloese_inland_innergemeinschaftlich', 10)->nullable()->default('');
                $table->string('steuer_aufwendung_inland_innergemeinschaftlich', 10)->nullable()->default('');
                $table->string('steuer_erloese_inland_eunormal', 10)->nullable()->default('');
                $table->string('steuer_aufwendung_inland_eunormal', 10)->nullable()->default('');
                $table->string('steuer_erloese_inland_euermaessigt', 10)->nullable()->default('');
                $table->string('steuer_aufwendung_inland_euermaessigt', 10)->nullable()->default('');
                $table->string('steuer_erloese_inland_export', 10)->nullable()->default('');
                $table->string('steuer_aufwendung_inland_import', 10)->nullable()->default('');
                $table->boolean('create_proformainvoice')->nullable()->default(0);
                $table->boolean('print_proformainvoice')->nullable()->default(0);
                $table->integer('proformainvoice_amount')->nullable()->default(0);
                $table->boolean('anzeigesteuerbelegebestellung')->nullable()->default(0);
                $table->boolean('autobestbeforebatch')->nullable()->default(0);
                $table->string('klarna_merchantid', 64)->default('');
                $table->string('klarna_sharedsecret', 64)->default('');
                $table->boolean('nurlagerartikel')->default(1);
                $table->boolean('paketmarkedrucken')->default(0);
                $table->boolean('lieferscheinedrucken')->default(0);
                $table->integer('lieferscheinedruckenmenge')->default(0);
                $table->boolean('auftragdrucken')->default(0);
                $table->integer('auftragdruckenmenge')->default(0);
                $table->boolean('druckennachtracking')->default(0);
                $table->boolean('exportdruckrechnungstufe1')->default(0);
                $table->integer('exportdruckrechnungstufe1menge')->default(0);
                $table->boolean('exportdruckrechnung')->default(0);
                $table->integer('exportdruckrechnungmenge')->default(0);
                $table->boolean('kommissionierlistestufe1')->default(0);
                $table->integer('kommissionierlistestufe1menge')->default(0);
                $table->boolean('fremdnummerscanerlauben')->default(0);
                $table->string('zvt100url')->default('');
                $table->string('zvt100port', 5)->default('');
                $table->boolean('production_show_only_needed_storages')->default(0);
                $table->boolean('produktion_extra_seiten')->default(0);
                $table->boolean('kasse_button_trinkgeldeckredit')->default(0);
                $table->integer('kasse_autologout')->default(0);
                $table->integer('kasse_autologout_abschluss')->default(0);
                $table->string('next_goodspostingdocument', 64)->nullable()->default('');
                $table->string('next_receiptdocument', 64)->nullable()->default('');
                $table->boolean('taxfromdoctypesettings')->default(0);
                $table->boolean('pos_sumarticles')->default(0);
                $table->boolean('manualtracking')->default(0);
                $table->integer('druckanhang')->nullable();
                $table->integer('mailanhang')->nullable();
                $table->boolean('allwaysautobestbeforebatch')->nullable()->default(0);
            });
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        if (!app()->environment('production')) {
            Schema::dropIfExists('projekt');
        }
    }
}
