<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateAdresseTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */

    public function up()
    {
      if (!app()->environment('production')) {
             Schema::create('adresse', function (Blueprint $table) {
                $table->id();
                 $table->string('name')->index();
                $table->boolean('abperfax')->default(0);
                $table->string('abpermail',128)->default('');
                $table->string('abteilung')->default('');
                $table->integer('abweichende_rechnungsadresse')->default(0);
                $table->string('abweichendeemailab',64)->nullable();
                $table->string('adresszusatz');
                $table->string('angebot_cc',128)->default('');
                $table->string('angebot_email',128)->default('');
                $table->string('angebot_fax_cc',128)->default('');
                $table->string('anschreiben',1024)->nullable();
                $table->string('ansprechpartner');
                $table->integer('anzeigesteuerbelege')->default(0);
                $table->decimal('arbeitszeitprowoche',10,2)->default(0.00);
                $table->string('art',32)->default('');
                $table->string('auftrag_cc',128)->default('');
                $table->string('auftrag_email',128)->default('');
                $table->string('auftrag_fax_cc',128)->default('');
                $table->string('bank');
                $table->string('bestellung_cc',128)->default('');
                $table->string('bestellung_email',128)->default('');
                $table->string('bestellung_fax_cc',128)->default('');
                $table->string('blz',64)->nullable();
                $table->decimal('bonus1',10,2)->nullable();
                $table->decimal('bonus10',10,2)->nullable();
                $table->decimal('bonus10_ab',10,2)->nullable();
                $table->decimal('bonus1_ab',10,2)->nullable();
                $table->decimal('bonus2',10,2)->nullable();
                $table->decimal('bonus2_ab',10,2)->nullable();
                $table->decimal('bonus3',10,2)->nullable();
                $table->decimal('bonus3_ab',10,2)->nullable();
                $table->decimal('bonus4',10,2)->nullable();
                $table->decimal('bonus4_ab',10,2)->nullable();
                $table->decimal('bonus5',10,2)->nullable();
                $table->decimal('bonus5_ab',10,2)->nullable();
                $table->decimal('bonus6',10,2)->nullable();
                $table->decimal('bonus6_ab',10,2)->nullable();
                $table->decimal('bonus7',10,2)->nullable();
                $table->decimal('bonus7_ab',10,2)->nullable();
                $table->decimal('bonus8',10,2)->nullable();
                $table->decimal('bonus8_ab',10,2)->nullable();
                $table->decimal('bonus9',10,2)->nullable();
                $table->decimal('bonus9_ab',10,2)->nullable();
                $table->string('bundesland',64)->nullable();
                $table->string('bundesstaat',32)->default('');
                $table->string('email')->index()->unique();
                $table->text('filiale')->nullable();
                $table->integer('firma');
                $table->boolean('firmensepa')->default(0);
                $table->boolean('folgebestaetigungsperre')->default(0);
                $table->text('freifeld1')->nullable();
                $table->text('freifeld10')->nullable();
                $table->text('freifeld11')->nullable();
                $table->text('freifeld12')->nullable();
                $table->text('freifeld13')->nullable();
                $table->text('freifeld14')->nullable();
                $table->text('freifeld15')->nullable();
                $table->text('freifeld16')->nullable();
                $table->text('freifeld17')->nullable();
                $table->text('freifeld18')->nullable();
                $table->text('freifeld19')->nullable();
                $table->text('freifeld2')->nullable();
                $table->text('freifeld20')->nullable();
                $table->text('freifeld3')->nullable();
                $table->text('freifeld4')->nullable();
                $table->text('freifeld5')->nullable();
                $table->text('freifeld6')->nullable();
                $table->text('freifeld7')->nullable();
                $table->text('freifeld8')->nullable();
                $table->text('freifeld9')->nullable();
                $table->integer('fromshop')->default(0);
                $table->date('geburtstag')->nullable();
                $table->boolean('geburtstagkalender')->default(0);
                $table->boolean('geburtstagskarte')->default(0);
                $table->integer('geloescht')->index();
                $table->integer('geworbenvon')->nullable();
                $table->string('glaeubigeridentnr')->default('');
                $table->string('gln',32)->default('')->index();
                $table->string('gutschrift_cc',128)->default('');
                $table->string('gutschrift_email',128)->default('');
                $table->string('gutschrift_fax_cc',128)->default('');
                $table->text('hinweis_einfuegen');
                $table->text('hinweistextlieferant');
                $table->string('iban',64)->nullable();
                $table->text('infoauftragserfassung');
                $table->string('inhaber');
                $table->integer('innendienst')->nullable()->index();
                $table->text('internetseite')->nullable();
                $table->integer('kalender_aufgaben')->nullable();
                $table->integer('kassiereraktiv')->default(0);
                $table->string('kassierernummer',10)->default('');
                $table->integer('kassiererprojekt')->default(0);
                $table->boolean('keinealtersabfrage')->default(0);
                $table->string('kennung')->nullable();
                $table->integer('kommissionskonsignationslager')->default(0);
                $table->string('konto',64)->nullable();
                $table->decimal('kreditlimit',10,2)->default(0.00);
                $table->integer('kundenfreigabe');
                $table->string('kundennummer')->index();
                $table->string('kundennummer_buchhaltung',20)->default('');
                $table->string('kundennummerlieferant');
                $table->string('land',64)->nullable();
                $table->decimal('lat',18,12)->nullable();
                $table->boolean('lead')->default(0);
                $table->string('lieferantennummer')->index();
                $table->string('lieferantennummer_buchhaltung',20)->default('');
                $table->string('lieferantennummerbeikunde',128)->nullable();
                $table->text('lieferbedingung');
                $table->string('lieferschein_cc',128)->default('');
                $table->string('lieferschein_email',128)->default('');
                $table->string('lieferschein_fax_cc',128)->default('');
                $table->boolean('lieferschwellenichtanwenden')->default(0);
                $table->integer('liefersperre')->nullable();
                $table->date('liefersperredatum')->nullable();
                $table->text('liefersperregrund')->nullable();
                $table->decimal('lng',18,12)->nullable();
                $table->timestamp('logdatei');
                $table->text('logfile')->nullable();
                $table->string('mandatsreferenz')->default('');
                $table->boolean('mandatsreferenzaenderung')->default(0);
                $table->string('mandatsreferenzart',64)->default('');
                $table->date('mandatsreferenzdatum')->nullable();
                $table->text('mandatsreferenzhinweis')->nullable();
                $table->string('mandatsreferenzwdhart',64)->default('');
                $table->string('marketingsperre');
                $table->string('mitarbeiternummer');
                $table->string('mlmabrechnung')->nullable();
                $table->integer('mlmaktiv')->nullable();
                $table->integer('mlmauszahlungprojekt')->default(0);
                $table->integer('mlmfestsetzen')->default(0);
                $table->date('mlmfestsetzenbis')->nullable();
                $table->boolean('mlmintranetgesamtestruktur')->default(0);
                $table->date('mlmlizenzgebuehrbis')->nullable();
                $table->integer('mlmmindestpunkte')->default(0);
                $table->integer('mlmmitmwst')->nullable();
                $table->string('mlmpositionierung')->nullable();
                $table->date('mlmvertragsbeginn')->nullable();
                $table->string('mlmwaehrungauszahlung')->nullable();
                $table->string('mlmwaehrungauszwahlung')->nullable();
                $table->decimal('mlmwartekonto',10,2)->default(0.00);
                $table->string('mobil',64)->nullable();
                $table->string('nachname',128)->default('');
                $table->string('ort');
                $table->integer('partner');
                $table->integer('passwort_gesendet');
                $table->string('paypal');
                $table->string('paypalinhaber');
                $table->string('paypalwaehrung');
                $table->string('plz',64)->nullable();
                $table->decimal('portofrei_aktiv',10,2)->nullable();
                $table->decimal('portofreiab',10,2)->default(0.00);
                $table->decimal('portofreiablieferant',10,2)->default(0.00);
                $table->boolean('portofreilieferant_aktiv')->default(0);
                $table->integer('projekt')->index('projekt');
                $table->decimal('provision',10,2)->nullable();
                $table->decimal('rabatt',10,2)->nullable();
                $table->decimal('rabatt1',10,2)->nullable();
                $table->decimal('rabatt2',10,2)->nullable();
                $table->decimal('rabatt3',10,2)->nullable();
                $table->decimal('rabatt4',10,2)->nullable();
                $table->decimal('rabatt5',10,2)->nullable();
                $table->integer('rabatte_festschreiben')->nullable();
                $table->text('rabattinformation')->nullable();
                $table->string('rechnung_abteilung',64)->nullable();
                $table->string('rechnung_adresszusatz',64)->nullable();
                $table->string('rechnung_anschreiben',64)->nullable();
                $table->string('rechnung_ansprechpartner',64)->nullable();
                $table->integer('rechnung_anzahlpapier')->nullable();
                $table->string('rechnung_bundesstaat',32)->default('');
                $table->string('rechnung_cc',128)->default('');
                $table->string('rechnung_email',64)->nullable();
                $table->string('rechnung_fax_cc',128)->default('');
                $table->string('rechnung_gln',32)->default('');
                $table->string('rechnung_land',64)->nullable();
                $table->string('rechnung_name',64)->nullable();
                $table->string('rechnung_ort',64)->nullable();
                $table->boolean('rechnung_papier')->default(0);
                $table->integer('rechnung_periode')->nullable();
                $table->integer('rechnung_permail')->nullable();
                $table->string('rechnung_plz',64)->nullable();
                $table->string('rechnung_strasse',64)->nullable();
                $table->string('rechnung_telefax',64)->nullable();
                $table->string('rechnung_telefon',64)->nullable();
                $table->string('rechnung_titel',64)->nullable();
                $table->string('rechnung_typ',64)->nullable();
                $table->string('rechnung_unterabteilung',64)->nullable();
                $table->string('rechnung_vorname',64)->nullable();
                $table->string('rechnungs_email',128)->default('');
                $table->integer('rechnungsadresse');
                $table->date('rolledatum')->nullable();
                $table->string('sachkonto',20)->default('');
                $table->boolean('serienbrief')->default(0);
                $table->text('sonstiges');
                $table->integer('sponsor')->nullable()->index();
                $table->string('sprache',32)->nullable();
                $table->string('steuer');
                $table->integer('steuerbefreit')->nullable();
                $table->string('steuernummer')->nullable();
                $table->string('strasse');
                $table->string('swift',64)->nullable();
                $table->string('telefax',64)->nullable();
                $table->string('telefon',64)->nullable();
                $table->string('titel',1024)->nullable();
                $table->integer('tour')->default(0);
                $table->integer('trackingsperre');
                $table->string('typ');
                $table->string('ueberstunden');
                $table->string('umsatzsteuer_lieferant',64)->default('');
                $table->string('unterabteilung');
                $table->integer('usereditid')->nullable()->index('user');
                $table->timestamp('useredittimestamp')->default('0000-00-00 00:00:00');
                $table->integer('ust_befreit');
                $table->string('ustid',64)->nullable();
                $table->string('verbandsnummer')->nullable();
                $table->boolean('verein_mitglied_aktiv')->nullable();
                $table->date('verein_mitglied_bis')->nullable();
                $table->date('verein_mitglied_seit')->nullable();
                $table->boolean('verein_spendenbescheinigung')->default(0);
                $table->integer('verrechnungskontoreisekosten')->default(0);
                $table->string('versandart');
                $table->string('versandartlieferant');
                $table->integer('vertrieb')->nullable()->index();
                $table->string('vorname')->nullable();
                $table->string('waehrung');
                $table->string('webid',1024)->nullable();
                $table->integer('zahlungskonditionen_festschreiben')->nullable();
                $table->string('zahlungsweise');
                $table->string('zahlungsweiseabo',64)->default('');
                $table->string('zahlungsweiselieferant');
                $table->string('zahlungszielskonto');
                $table->string('zahlungszielskontolieferant');
                $table->string('zahlungszieltage');
                $table->string('zahlungszieltagelieferant');
                $table->string('zahlungszieltageskonto');
                $table->string('zahlungszieltageskontolieferant');
                $table->text('zollinformationen');
             });
     }
}


     /**
      * Reverse the migrations.
      *
      * @return void
      */
     public function down()
     {
       if (!app()->environment('production')) {
             Schema::dropIfExists('adresse');
     }
   }
 }
