<?php

namespace App\Http\Controllers;

use App\Models\Adresse;
use App\Models\AdresseRolle;
use App\Models\Project;
use App\Models\XentralUser;
use Illuminate\Http\Request;
use App\Models\UserRight;
use View;

class UserRightController extends Controller
{
    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
      // load the create form (app/views/userrights/create.blade.php)
      return View('userrights.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
      $rechte =
      [
      "abrechnung" => ['zeiterfassung'],

      "adresse" => ['abrechnungzeit',
      'abrechnungzeitabgeschlossen',
      'artikel',
      'abrechnungzeitdelete',
      'delkontakt',
      'createdokument',
      'kundeartikel',
      'stundensatzdelete',
      'stundensatz',
      'newkontakt',
      'minidetail',
      'lohn',
      'stundensatzedit',
      'multilevel',
      'addposition',
      'adressebestellungmarkieren',
      'ansprechpartner',
      'ansprechpartnereditpopup',
      'ansprechpartnerpopup',
      'artikeleditpopup',
      'auftraege',
      'autocomplete',
      'edit',
      'downartikel',
      'create',
      'briefpdf',
      'delete',
      'delartikel',
      'briefdelete',
      'brief',
      'dateien',
      'email',
      'kundevorlage',
      'list',
      'positioneneditpopup',
      'ustprfedit',
      'ustprfneu',
      'rolecreate',
      'lieferadresse',
      'emaileditpopup',
      'briefeditpopup',
      'kontakthistorie',
      'lieferadresseneditpopup',
      'roledel',
      'suchmaske',
      'upartikel',
      'rolledelete',
      'lieferadressepopup',
      'lieferantartikel',
      'kontakthistorieeditpopup',
      'ustpopup',
      'lieferantvorlage',
      'offenebestellungen',
      'ustprf'],

      "ajax" => ['ansprechpartner',
      'lieferadresse',
      'filter',
      'table',
      'tableposition',
      'tooltipsuche',
      'tcgetnextartikelnummer'],

      "angebot" => ['addposition'],

      "api" => ['shopimages'],

      "arbeitsnachweis" => ['abschicken',
      'addposition',
      'copy',
      'createfromproject',
      'delarbeitsnachweisposition',
      'list',
      'editable',
      'downarbeitsnachweisposition',
      'delete',
      'livetabelle',
      'positionen',
      'protokoll',
      'uparbeitsnachweisposition',
      'minidetail',
      'pdf',
      'edit',
      'create',
      'freigabe',
      'positioneneditpopup',
      'inlinepdf',
      'abrechnung'],

      "artikel"  => ['ausreservieren',
      'instueckliste',
      'einkaufdisable',
      'lagerlampe',
      'schliessen',
      'stuecklisteempty',
      'provision',
      'statistik',
      'produktion',
      'stuecklisteetiketten',
      'minidetail',
      'shopexport',
      'stuecklisteimport',
      'verkaufdisable',
      'shopexportfiles',
      'stuecklisteupload',
      'umlagern',
      'multilevel',
      'ajaxwerte',
      'delete',
      'einkaufcopy',
      'newlist',
      'projekte',
      'delstueckliste',
      'einkaufdelete',
      'offeneauftraege',
      'verkaufeditpopup',
      'offenebestellungen',
      'reservierung',
      'stueckliste',
      'upstueckliste',
      'wareneingang',
      'downstueckliste',
      'copy',
      'edit',
      'einkaufeditpopup',
      'list',
      'onlineshop',
      'verkauf',
      'seriennummern',
      'verkaufcopy',
      'create',
      'editstueckliste',
      'dateien',
      'einkauf',
      'etiketten',
      'profisuche',
      'verkaufdelete',
      'artikelfreifelder',
      'artikelfreifelderedit',
      'artikelfreifeldersave',
      'baumedit',
      'srnlageredit',
      'zertifikate',
      'srnadresseedit',
      'schnellanlegen',
      'lagersync',
      'chargedelete',
      'copyedit',
      'srnlagerdelete',
      'mindesthaltbarkeitsdatum',
      'demo',
      'chargen',
      'fremdnummern',
      'thumbnail',
      'eigenschaftencopy',
      'artikelfreifelderdelete',
      'mhddelete',
      'einlagern',
      'eigenschaftensuche',
      'rohstoffeempty',
      'shopimport',
      'fremdnummerndelete',
      'fremdnummernedit',
      'auslagern',
      'rohstoffe',
      'baum',
      'fremdnummernsave',
      'eigenschaften',
      'eigenschafteneditpopup',
      'editrohstoffe',
      'rabatt',
      'belege',
      'stuecklisteexport',
      'baumajax',
      'delrohstoffe',
      'copysave',
      'lager',
      'baumdetail',
      'eigenschaftendelete'],

      "artikelbaum" => ['change',
      'list',
      'loeschen',
      'detail',
      'baumajax'],

      "artikeleigenschaften" => ['create',
      'list',
      'delete',
      'edit'],

      "artikeleinheit" => ['create',
      'edit',
      'delete',
      'list'],

      "artikelgruppen" => ['delete',
      'create',
      'edit',
      'list'],

      "artikelkalkulation" => ['delete',
      'ekladen',
      'kalkekladen',
      'edittag',
      'gesperrt',
      'list',
      'edit',
      'savetag',
      'save'],

      "artikelkategorien" => ['delete',
      'create',
      'edit',
      'list'],

      "artikel_fremdnummern" => ['edit',
      'save',
      'delete',
      'list'],

      "artikel_texte" => ['delete',
      'edit',
      'list',
      'save'],

      "auftrag" => ['abschluss',
      'inlinepdf',
      'anfrage',
      'abschicken',
      'checkdisplay',
      'downauftragposition',
      'list',
      'positionen',
      'uststart',
      'copy',
      'edit',
      'livetabelle',
      'positioneneditpopup',
      'search',
      'verfuegbar',
      'addposition',
      'create',
      'editable',
      'minidetail',
      'proforma',
      'shopexport',
      'versand',
      'dateien',
      'freigabe',
      'nachlieferung',
      'protokoll',
      'teillieferung',
      'ausversand',
      'delauftragposition',
      'rechnung',
      'tracking',
      'zahlungsmahnungswesen',
      'berechnen',
      'delete',
      'lieferschein',
      'pdf',
      'reservieren',
      'upauftragposition',
      'zahlungsmail',
      'summe'],

      "bestellung" => ['auftrag',
      'livetabelle',
      'inlinepdf',
      'abschicken',
      'delbestellungposition',
      'positioneneditpopup',
      'addposition',
      'delete',
      'list',
      'protokoll',
      'downbestellungposition',
      'copy',
      'edit',
      'minidetail',
      'upbestellungposition',
      'create',
      'editable',
      'pdf',
      'dateien',
      'freigabe',
      'positionen'],

      "bestellvorschlag" => ['create',
      'tabelle',
      'list'],

      "dateien" => ['abschicken',
      'archiv',
      'artikel',
      'freigabe',
      'kundeuebernehmen',
      'versand',
      'lieferadresseneu',
      'zahlung',
      'protokoll',
      'listfreigegebene',
      'lieferadresseauswahl',
      'edit',
      'send',
      'create',
      'delete',
      'list'],

      "etiketten" => ['create',
      'edit',
      'list',
      'delete'],

      "generic" => ['edit',
      'reiter_delete',
      'reiter_up',
      'reiter_down'],

      "gutschrift" => ['zahlungseingang',
      'zahlungsmahnungswesen',
      'inlinepdf',
      'abschicken',
      'edit',
      'minidetail',
      'storno',
      'addposition',
      'editable',
      'pdf',
      'upgutschriftposition',
      'create',
      'freigabe',
      'positionen',
      'delete',
      'positioneneditpopup',
      'delgutschriftposition',
      'list',
      'protokoll',
      'downgutschriftposition',
      'livetabelle'],

      "hauptmenu" => ['list'],

      "inhalt" => ['delete',
      'listshop',
      'create',
      'edit',
      'list'],

      "inventur" => ['abschicken',
      'addposition',
      'buchen',
      'copy',
      'create',
      'createfromproject',
      'freigabe',
      'editable',
      'edit',
      'downinventurposition',
      'delinventurposition',
      'delete',
      'list',
      'livetabelle',
      'minidetail',
      'pdf',
      'positionen',
      'positioneneditpopup',
      'protokoll',
      'upinventurposition',
      'automatisch'],

      "kalender" => ['data',
      'eventdata',
      'taskstatus',
      'update',
      'delete',
      'list'],

      "kasse" => ['exportieren'],

      "lager" =>['auslagernproduktion',
      'deleteplatz',
      'buchenzwischenlagerdelete',
      'lagerpdfsammelentnahme',
      'inventurladen',
      'artikelentfernen',
      'artikelentfernenreserviert',
      'artikelfuerlieferungen',
      'ausgehend',
      'bestand',
      'buchenzwischenlager',
      'bucheneinlagern',
      'buchenauslagern',
      'buchen',
      'bewegungpopup',
      'bewegung',
      'create',
      'delete',
      'edit',
      'etiketten',
      'platzeditpopup',
      'list',
      'platz',
      'inventur',
      'produktionslager',
      'regaletiketten',
      'reservierungen',
      'zwischenlager',
      'nachschublager'],

      "lagermobil" => ['artikelentfernen',
      'ausgehend',
      'auslagernproduktion',
      'auslagern',
      'artikelentfernenreserviert',
      'bewegung',
      'buchen',
      'buchenauslagern',
      'bucheneinlagern',
      'artikelfuerlieferungen',
      'buchenzwischenlager',
      'delete',
      'buchenzwischenlagerdelete',
      'create',
      'differenzen',
      'deleteplatz',
      'bewegungpopup',
      'edit',
      'einlagern',
      'differenzenlagerplatz',
      'differenzenlagerplatzsave',
      'etiketten',
      'inhalt',
      'differenzenlagerplatzedit',
      'lagerpdfsammelentnahme',
      'letztebewegungen',
      'platz',
      'lpumlagern',
      'nachschublager',
      'list',
      'reservierungen',
      'produktionslager',
      'schnelleinlagern',
      'zwischenlager',
      'regaletiketten',
      'wert',
      'platzeditpopup'],

      "lieferschein" => ['paketmarke',
      'inlinepdf',
      'abschicken',
      'addposition',
      'copy',
      'create',
      'delete',
      'dellieferscheinposition',
      'list',
      'freigabe',
      'editable',
      'edit',
      'downlieferscheinposition',
      'livetabelle',
      'minidetail',
      'pdf',
      'positionen',
      'positioneneditpopup',
      'uplieferscheinposition',
      'protokoll'],

      "linkeditor" => ['delete',
      'massedit',
      'deleterule',
      'help',
      'list',
      'status'],

      "lohnabrechnung" => ['details',
      'list',
      'minidetail',
      'monatsuebersicht'],

      "mobile" => ['auslagern',
      'cancel',
      'einlagern',
      'list',
      'umlagern'],

      "multilevel" => ['create',
      'edit',
      'list'],

      "multiorderpicking" => ['edit',
      'fehler',
      'list',
      'label',
      'minidetail',
      'versandzentrum',
      'listmobile'],

      "paketmarke" => ['create',
      'tracking'],

      "rechnung" => ['zahlungseingang',
      'forderungsverlust',
      'inlinepdf',
      'manuellbezahltentfernen',
      'manuellbezahltmarkiert',
      'multilevel',
      'abschicken',
      'destop',
      'freigabe',
      'mahnpdf',
      'search',
      'addposition',
      'downrechnungposition',
      'gutschrift',
      'mahnwesen',
      'pdf',
      'skonto',
      'copy',
      'dta',
      'mahnweseneinstellungen',
      'positionen',
      'stop',
      'create',
      'edit',
      'lastschrift',
      'positioneneditpopup',
      'uprechnungposition',
      'delete',
      'editable',
      'list',
      'protokoll',
      'delrechnungposition',
      'livetabelle',
      'minidetail',
      'zahlungsmahnungswesen'],

      "rechnungslauf" => ['archiv',
      'create',
      'edit',
      'list',
      'mahnwesen',
      'zahlungseingang',
      'artikel',
      'rechnungslauf'],

      "reisekostenart" =>['create',
      'delete',
      'edit',
      'list'],

      "seriennummern" => ['create',
      'edit',
      'delete',
      'lager',
      'log',
      'list',
      'produktion'],

      "stornierungen" => ['create',
      'edit',
      'bezahlt',
      'list'],

      "survey" => ['list'],

      "ticket_old" => ['antwort',
      'beantwortet',
      'delete',
      'edit',
      'freigabe',
      'create',
      'list',
      'assistent'],

      "uebersetzung" => ['main'],

      "verrechnungsart" => ['create',
      'delete',
      'edit'],

      "versanderzeugen" => ['einzel',
      'frankieren',
      'list',
      'main',
      'offene',
      'korrektur',
      'gelesen',
      'delete'],

      "vmajax" => ['vmautoversanddrucken',
      'vmautoversanddruckencheckbatch'],

      "wareneingang" => ['main',
      'removevorgang',
      'vorgang',
      'help',
      'create',
      'distriabschluss',
      'distribution',
      'distrietiketten',
      'distriinhalt',
      'list',
      'paketabschliessen',
      'paketabsender',
      'paketannahme',
      'paketetikett',
      'rmalist',
      'rmadetail',
      'paketzustand',
      'manuellerfassen',
      'minidetail'],

      "warteschlangen" => ['create',
      'delete',
      'edit',
      'list'],

      "welcome" => ['help',
      'info',
      'list',
      'start',
      'settings',
      'addnote',
      'delnote',
      'movenote',
      'oknote',
      'pinwand',
      'upgrade',
      'startseite',
      'css',
      'logo',
      'editvorgang',
      'logout',
      'main',
      'login',
      'vorgang',
      'removevorgang'],

      "wiki" => ['alle',
      'create',
      'delete',
      'edit',
      'list',
      'rename',
      'dateien'],

      "wizard" => ['adresse',
      'create',
      'list'],

      "zeiterfassung" => ['abrechnenpdf',
      'listuser',
      'minidetail',
      'arbeitspaket',
      'create',
      'delete',
      'details',
      'edit',
      'list']
      ];

          // store
          $user = XentralUser::find($request->id);
          foreach ($rechte as $module) {
            foreach ($module as $action) {
              UserRight::create([
                'user'      =>  $user->id,
                'module'      =>  $module,
                'action'      =>  $action,
                'permission'  =>  1,
              ]);
              Session::flash('message', 'Successfully created Benutzer!');
              return redirect::to('/users/id=' . $newuser->id);        }
          }
    }

    /**
     * Display the specified resource.
     */
    public function show($id)
    {
        $user = XentralUser::find($id);
        $userrights = $user->userright()->get();

        // get all the $userrightes
        $userrightes = UserRight::paginate(10);
        return View('userrights.index',
            compact('userrightes'))->with(array(
            "user" => $user,
            "userrights" => $userrights,
           ));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(userright $userright)
    {
    return View('userrights.edit',compact('userright'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, userright $userright)
    {
      $this->validate($request, [
        'action'       => 'required',
        'module'       => 'required',
        'permission'   => 'required',
        'user'      => 'required|numeric',
         ]);

         $userright->update($request->all());
         return back();
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(userright $userright)
    {
      $userright->delete();
       return back();
    }
}
